#!/bin/bash

###
# This script provides a simple pomodoro timer. Check out the following link to
# learn more about the Pomodoro Technique:
# http://cirillocompany.de/pages/pomodoro-technique/
#
# This script repeats the Pomodoro cycle indefinitely until it is killed e.g.
# using Ctrl+C
#
# Usage:
#   pomodoro -h
###

YELLOW='\033[0;33m'
NC='\033[0m'


beep=$(<beeps)

audio_enabled=true
notification_enabled=true
print_enabled=true
minutes_work=25
minutes_short_break=10
minutes_long_break=25

warn(){
    echo "${YELLOW}Warning:${NC} $*"
}

check_prog() {
    if ! command -v "$1" > /dev/null; then
        warn "Command $1 not available!"
        return 1
    fi
    return 0
}

message() {
    if $notification_enabled; then
        notify-send "$@"
    fi

    if $print_enabled; then
        echo "$(date +%H:%M)   $*"
    fi

    if $audio_enabled; then
        echo $beep | base64 --decode | mpg123 -q -
    fi
}

work() {
    message "Get your work done!"
    sleep "${minutes_work}m"
}

pause() {
    message "Take a break for ${1} minutes!"
    sleep "${1}m"
}

usage() {
    echo "Usage: $0 [OPTIONS]"
    echo
    echo "OPTIONS:"
    echo "  -h        print this help and exit"
    echo "  -a        disable audio"
    echo "  -n        disable notification"
    echo "  -p        disable printing to stdout"
    echo "  -t w:s:l  set timers. Format is 'work_minutes:short_break_minutes:long_break_minutes'"
}

while getopts "hapnt:" opt; do
    case $opt in
        h)
            usage
            exit
            ;;
        a)
            audio_enabled=false
            ;;
        p)
            print_enabled=false
            ;;
        n)
            notification_enabled=false
            ;;
        t)
            time_format="$OPTARG"
            ;;
        ?)
            usage
            exit 1
            ;;
    esac
done

if [ -n "$time_format" ]; then
    IFS=":" read -ra times <<< "$time_format"
    minutes_work=${times[0]}
    minutes_short_break=${times[1]}
    minutes_long_break=${times[2]}
fi

if $audio_enabled; then
    if ! (check_prog base64 && check_prog mpg123); then
        audio_enabled=false
        warn "Audio will be disabled!"
    fi
fi

if $notification_enabled; then
    if ! check_prog notify-send; then
        notification_enabled=false
        warn "Notifications will be disabled!"
    fi
fi

while true; do
    work
    pause "$minutes_short_break"
    work
    pause "$minutes_short_break"
    work
    pause "$minutes_short_break"
    work
    pause "$minutes_long_break"
done
